name: Github to Jira Automation

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_REST_API }}
        
#     - name: Transition issue
#       uses: atlassian/gajira-transition@master
#       with:
#         issue: ${{ github.head_ref }}
#         transition: "In progress"

#     - name: Jira find and transition issues
#       uses: chontawee/gj-find-transition-issues@1.0.4
#       with:
#          issue: ${{ github.head_ref }}
#          transition: "Peer Review"

    - name: Jira find and transition issues
      uses: chontawee/gj-find-transition-issues@1.0.4
      with:
        issuetypes: Task,Epic
        transitions: Peer Review,Peer Review
