on:
  pull_request:
    types: [closed]
    branches: main # PRs to the following branches will trigger the workflow
jobs:
  Executing:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Head Branch Name
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
         echo Compare Branch Name = "$GITHUB_HEAD_REF"
         echo Base Branch Name = "$GITHUB_BASE_REF"

      - name: Spliting of the output
      - uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: "$GITHUB_HEAD_REF"
          split-by: '/'
          
      - name: Printing of the output
        run: |
          first="${{ steps.split.outputs._0}}"
          second="${{ steps.split.outputs._1}}" 
          echo first element Name = "$first"  
          echo second element Name = "$second"  
