on:
#   pull_request:
#     types: [closed]
#     branches: main # PRs to the following branches will trigger the workflow
  push:
    branches: new-CICD-45/sample-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Head Branch Name
        id: data
        run: echo "::set-output name=COMPARE::${GITHUB_HEAD_REF}"
        
      - name: Print Base Branch Name  
        run: echo "::set-output name=BASE::${GITHUB_BASE_REF}"
        
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ steps.data.outputs.COMPARE }}
          separator: '/'
      - name: Printing the Names 
        run: |
          echo ${{ steps.split.outputs._0 }}
