on:
  pull_request:
    types: [closed]
    branches: main # PRs to the following branches will trigger the workflow
jobs:
  printing:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print Head Branch Name
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      run: |
      Compare_Name=$(echo "$GITHUB_HEAD_REF")
      echo "Compare_Name: Compare_Name is : $Compare_Name"
      echo ::set-output name=Compare_Name::"$Compare_Name"
