on:
  pull_request:
    types: [closed]
    branches: main # PRs to the following branches will trigger the workflow
jobs:
  build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print Head Branch Name
      id: data
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      run: |
       echo ::set-output name=COMPARE::"$GITHUB_HEAD_REF"
       echo ::set-output name=BASE::"$GITHUB_BASE_REF"
       
    - uses: jungwinter/split@v2
      id: split
      with:
          msg: ${{ steps.headBranch.outputs.COMPARE }}
          separator: '/'

    - name: release package
      run: |
        echo ${{ steps.split.outputs._0 }}
        echo ${{ steps.split.outputs._1 }}  


#     - uses: rishabhgupta/split-by@v1
#       id: split
#       with:
#        string: "$GITHUB_HEAD_REF"
#        split-by: '/'
       
#     - name: release package
#       run: |
#         echo ${{ steps.split.outputs._0 }}
#         echo ${{ steps.split.outputs._1 }}    
          
