on:
  pull_request:
    types: [closed]
    branches: main # PRs to the following branches will trigger the workflow
jobs:
  build:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print Head Branch Name
      id: data
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      run: |
       echo ::set-output name=COMPARE::"$GITHUB_HEAD_REF"
       echo ::set-output name=BASE::"$GITHUB_BASE_REF"
       
    - uses: jungwinter/split@v2
      id: split
      with:
          msg: ${{ steps.data.outputs.COMPARE }}
          separator: '/'

    - name: release package
      run: |
        echo ${{ steps.split.outputs._0 }}
        echo ${{ steps.split.outputs._1 }}  
        
    - uses: jungwinter/split@v2
      id: split2
      with:
          msg: ${{ steps.split.outputs._0 }}
          separator: '-'

    - name: release package
      run: |
        echo ${{ steps.split2.outputs._0 }}
        echo ${{ steps.split2.outputs._1 }}  
        echo ${{ steps.split2.outputs._2 }}  
