name: repo_name_printing

on: push

jobs:
  my-job:
    name: Pulkit Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Print a manual name.
        env:
          MY_VAR: Hey, The name of this repo is 
        run: |
          echo $MY_VAR ${{ github.event.repository.name }}.
